/*
    Created by Quo
*/
 



-- Insert Biome info into player select screen

INSERT INTO PlayerItems 
		(Domain,CivilizationType,LeaderType,Type,Name,Description,Icon,SortIndex)
VALUES ('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT_ROUGHRIDER', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_BRAZIL', 'LEADER_PEDRO', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_AUSTRALIA', 'LEADER_JOHN_CURTIN', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CANADA', 'LEADER_LAURIER', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GRAN_COLOMBIA', 'LEADER_SIMON_BOLIVAR', 'QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_AZTEC', 'LEADER_MONTEZUMA', 'QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CREE', 'LEADER_POUNDMAKER', 'QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAPUCHE', 'LEADER_LAUTARO', 'QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INCA', 'LEADER_PACHACUTI', 'QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAYA', 'LEADER_LADY_SIX_SKY', 'QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ZULU', 'LEADER_SHAKA', 'QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_MVEMBA', 'QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_MANSA_MUSA', 'QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_NUBIA', 'LEADER_AMANITORE', 'QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ETHIOPIA', 'LEADER_MENELIK', 'QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN', 'QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CYRUS', 'QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SUMERIA', 'LEADER_GILGAMESH', 'QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN', 'QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_BABYLON_STK', 'LEADER_HAMMURABI', 'QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_CHANDRAGUPTA', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_GANDHI', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KHMER', 'LEADER_JAYAVARMAN', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI_ALT', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_BARBAROSSA', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SPAIN', 'LEADER_PHILIP_II', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILHELMINA', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_ELEANOR_FRANCE', 'QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
	
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_GORGO', 'QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_PERICLES', 'QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MACEDON', 'LEADER_ALEXANDER', 'QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_TRAJAN', 'QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_BYZANTIUM', 'LEADER_BASIL', 'QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARDRADA', 'QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_SUK_ICELAND', 'LEADER_SUK_INGOLFUR', 'QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SWEDEN', 'LEADER_KRISTINA', 'QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_SCYTHIA', 'LEADER_TOMYRIS', 'QUO_TRAIT_BIOME_ASIAN_STEPPE', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_DESCRIPTION', 'ICON_UNIT_GREAT_GENERAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_GENGHIS_KHAN', 'QUO_TRAIT_BIOME_ASIAN_STEPPE', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_DESCRIPTION', 'ICON_UNIT_GREAT_GENERAL', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_HOJO', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEONDEOK', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_GITARJA', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAORI', 'LEADER_KUPE', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_VIETNAM', 'LEADER_LADY_TRIEU', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA', 'QUO_TRAIT_BIOME_UK', 'LOC_QUO_TRAIT_BIOME_UK_NAME', 'LOC_QUO_TRAIT_BIOME_UK_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SCOTLAND', 'LEADER_ROBERT_THE_BRUCE', 'QUO_TRAIT_BIOME_UK', 'LOC_QUO_TRAIT_BIOME_UK_NAME', 'LOC_QUO_TRAIT_BIOME_UK_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELEANOR_ENGLAND', 'QUO_TRAIT_BIOME_UK', 'LOC_QUO_TRAIT_BIOME_UK_NAME', 'LOC_QUO_TRAIT_BIOME_UK_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GAUL', 'LEADER_AMBIORIX', 'QUO_TRAIT_BIOME_UK', 'LOC_QUO_TRAIT_BIOME_UK_NAME', 'LOC_QUO_TRAIT_BIOME_UK_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_POLAND', 'LEADER_JADWIGA', 'QUO_TRAIT_BIOME_EAST_EUROPE', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5) ,	
		('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_BIOME_EAST_EUROPE', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5)  ,
		('Players:Expansion2_Players', 'CIVILIZATION_GEORGIA', 'LEADER_TAMAR', 'QUO_TRAIT_BIOME_EAST_EUROPE', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_HUNGARY', 'LEADER_MATTHIAS_CORVINUS', 'QUO_TRAIT_BIOME_EAST_EUROPE', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5)		,
		
		('Players:Expansion2_Players', 'CIVILIZATION_PHOENICIA', 'LEADER_DIDO', 'QUO_TRAIT_BIOME_NORTH_AFRICA', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_DESCRIPTION', 'ICON_UNIT_GREAT_MERCHANT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA', 'QUO_TRAIT_BIOME_NORTH_AFRICA', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_DESCRIPTION', 'ICON_UNIT_GREAT_MERCHANT', 5)  ;
		
		
-- Friendship gifts
INSERT INTO PlayerItems 
		(Domain,CivilizationType,LeaderType,Type,Name,Description,Icon,SortIndex)
VALUES ('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT', 'QUO_TRAIT_FRIENDS_AMERICA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_AMERICA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_BRAZIL', 'LEADER_PEDRO', 'QUO_TRAIT_FRIENDS_BRAZIL', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_BRAZIL_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_AUSTRALIA', 'LEADER_JOHN_CURTIN', 'QUO_TRAIT_FRIENDS_AUSTRALIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_AUSTRALIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CANADA', 'LEADER_LAURIER', 'QUO_TRAIT_FRIENDS_CANADA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_CANADA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_GRAN_COLOMBIA', 'LEADER_SIMON_BOLIVAR', 'QUO_TRAIT_FRIENDS_GRAN_COLOMBIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_GRAN_COLOMBIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5),
		
		('Players:Expansion2_Players', 'CIVILIZATION_AZTEC', 'LEADER_MONTEZUMA', 'QUO_TRAIT_FRIENDS_AZTEC', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_AZTEC_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CREE', 'LEADER_POUNDMAKER', 'QUO_TRAIT_FRIENDS_CREE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_CREE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAPUCHE', 'LEADER_LAUTARO', 'QUO_TRAIT_FRIENDS_MAPUCHE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MAPUCHE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INCA', 'LEADER_PACHACUTI', 'QUO_TRAIT_FRIENDS_INCA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_INCA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_MAYA', 'LEADER_LADY_SIX_SKY', 'QUO_TRAIT_FRIENDS_MAYA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MAYA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_NUBIA', 'LEADER_AMANITORE', 'QUO_TRAIT_FRIENDS_NUBIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_NUBIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ZULU', 'LEADER_SHAKA', 'QUO_TRAIT_FRIENDS_ZULU', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ZULU_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_MVEMBA', 'QUO_TRAIT_FRIENDS_KONGO', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_KONGO_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_MANSA_MUSA', 'QUO_TRAIT_FRIENDS_MALI', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MALI_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ETHIOPIA', 'LEADER_MENELIK', 'QUO_TRAIT_FRIENDS_ETHIOPIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ETHIOPIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN', 'QUO_TRAIT_FRIENDS_ARABIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ARABIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CYRUS', 'QUO_TRAIT_FRIENDS_PERSIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_PERSIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SUMERIA', 'LEADER_GILGAMESH', 'QUO_TRAIT_FRIENDS_SUMERIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_SUMERIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA', 'QUO_TRAIT_FRIENDS_EGYPT', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_EGYPT_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN', 'QUO_TRAIT_FRIENDS_OTTOMAN', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_OTTOMAN_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN', 'QUO_TRAIT_FRIENDS_CHINA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_CHINA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_CHANDRAGUPTA', 'QUO_TRAIT_FRIENDS_INDIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_INDIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_GANDHI', 'QUO_TRAIT_FRIENDS_INDIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_INDIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KHMER', 'LEADER_JAYAVARMAN', 'QUO_TRAIT_FRIENDS_KHMER', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_KHMER_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI', 'QUO_TRAIT_FRIENDS_FRANCE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_FRANCE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_BARBAROSSA', 'QUO_TRAIT_FRIENDS_GERMANY', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_GERMANY_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SPAIN', 'LEADER_PHILIP_II', 'QUO_TRAIT_FRIENDS_SPAIN', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_SPAIN_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILHELMINA', 'QUO_TRAIT_FRIENDS_NETHERLANDS', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_NETHERLANDS_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_ELEANOR_FRANCE', 'QUO_TRAIT_FRIENDS_FRANCE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_FRANCE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
	
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_GORGO', 'QUO_TRAIT_FRIENDS_GREECE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_GREECE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_PERICLES', 'QUO_TRAIT_FRIENDS_GREECE', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_GREECE_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MACEDON', 'LEADER_ALEXANDER', 'QUO_TRAIT_FRIENDS_MACEDON', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MACEDON_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_TRAJAN', 'QUO_TRAIT_FRIENDS_ROME', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ROME_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_PHOENICIA', 'LEADER_DIDO', 'QUO_TRAIT_FRIENDS_PHOENICIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_PHOENICIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARDRADA', 'QUO_TRAIT_FRIENDS_NORWAY', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_NORWAY_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_SUK_ICELAND', 'LEADER_SUK_INGOLFUR', 'QUO_TRAIT_FRIENDS_ICELAND', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ICELAND_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SWEDEN', 'LEADER_KRISTINA', 'QUO_TRAIT_FRIENDS_SWEDEN', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_SWEDEN_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_SCYTHIA', 'LEADER_TOMYRIS', 'QUO_TRAIT_FRIENDS_SCYTHIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_SCYTHIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_GENGHIS_KHAN', 'QUO_TRAIT_FRIENDS_MONGOLIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MONGOLIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_HOJO', 'QUO_TRAIT_FRIENDS_HOJO', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_JAPAN_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEONDEOK', 'QUO_TRAIT_FRIENDS_KOREA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_KOREA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_GITARJA', 'QUO_TRAIT_FRIENDS_INDONESIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_INDONESIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAORI', 'LEADER_KUPE', 'QUO_TRAIT_FRIENDS_MAORI', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_MAORI_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA', 'QUO_TRAIT_FRIENDS_ENGLAND', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ENGLAND_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SCOTLAND', 'LEADER_ROBERT_THE_BRUCE', 'QUO_TRAIT_FRIENDS_SCOTLAND', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_SCOTLAND_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELEANOR_ENGLAND', 'QUO_TRAIT_FRIENDS_ENGLAND', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_ENGLAND_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_POLAND', 'LEADER_JADWIGA', 'QUO_TRAIT_FRIENDS_POLAND', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_POLAND_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5) ,	
		('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_FRIENDS_RUSSIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_RUSSIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5)  ,
		('Players:Expansion2_Players', 'CIVILIZATION_GEORGIA', 'LEADER_TAMAR', 'QUO_TRAIT_FRIENDS_GEORGIA', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_GEORGIA_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_HUNGARY', 'LEADER_MATTHIAS_CORVINUS', 'QUO_TRAIT_FRIENDS_HUNGARY', 'LOC_QUO_TRAIT_FRIEND_GIFT_NAME', 'LOC_QUO_TRAIT_FRIENDS_HUNGARY_DESCRIPTION', 'ICON_UNIT_SUMERIAN_WAR_CART', 5)		;

	
-- governors		
INSERT INTO PlayerItems 
		(Domain,CivilizationType,LeaderType,Type,Name,Description,Icon,SortIndex)
VALUES ('Players:Expansion2_Players', 'CIVILIZATION_AMERICA', 'LEADER_T_ROOSEVELT', 'QUO_TRAIT_BIOME_NEW_WORLD_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION', 'ICON_UNIT_RANGER', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_BRAZIL', 'LEADER_PEDRO', 'QUO_TRAIT_BIOME_NEW_WORLD_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION', 'ICON_UNIT_RANGER', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_AUSTRALIA', 'LEADER_JOHN_CURTIN', 'QUO_TRAIT_BIOME_NEW_WORLD_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CANADA', 'LEADER_LAURIER', 'QUO_TRAIT_BIOME_NEW_WORLD_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GRAN_COLOMBIA', 'LEADER_SIMON_BOLIVAR', 'QUO_TRAIT_BIOME_NEW_WORLD_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION', 'ICON_UNIT_RANGER', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_AZTEC', 'LEADER_MONTEZUMA', 'QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_CREE', 'LEADER_POUNDMAKER', 'QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAPUCHE', 'LEADER_LAUTARO', 'QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INCA', 'LEADER_PACHACUTI', 'QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAYA', 'LEADER_LADY_SIX_SKY', 'QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_CAMP', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ZULU', 'LEADER_SHAKA', 'QUO_TRAIT_BIOME_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KONGO', 'LEADER_MVEMBA', 'QUO_TRAIT_BIOME_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MALI', 'LEADER_MANSA_MUSA', 'QUO_TRAIT_BIOME_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_NUBIA', 'LEADER_AMANITORE', 'QUO_TRAIT_BIOME_NORTH_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_NAZCA_LINE', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ARABIA', 'LEADER_SALADIN', 'QUO_TRAIT_BIOME_ARABESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CYRUS', 'QUO_TRAIT_BIOME_ARABESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SUMERIA', 'LEADER_GILGAMESH', 'QUO_TRAIT_BIOME_ARABESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_OTTOMAN', 'LEADER_SULEIMAN', 'QUO_TRAIT_BIOME_ARABESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION', 'ICON_UNIT_MISSIONARY', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_CHINA', 'LEADER_QIN', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_CHANDRAGUPTA', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDIA', 'LEADER_GANDHI', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KHMER', 'LEADER_JAYAVARMAN', 'QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_GOV_DESCRIPTION', 'ICON_UNIT_OBSERVATION_BALLOON', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_CATHERINE_DE_MEDICI', 'QUO_TRAIT_BIOME_WEST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_BARBAROSSA', 'QUO_TRAIT_BIOME_WEST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SPAIN', 'LEADER_PHILIP_II', 'QUO_TRAIT_BIOME_WEST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILHELMINA', 'QUO_TRAIT_BIOME_WEST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_FRANCE', 'LEADER_ELEANOR_FRANCE', 'QUO_TRAIT_BIOME_WEST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FORT', 5) ,
	
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_GORGO', 'QUO_TRAIT_BIOME_ROMANESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_GREECE', 'LEADER_PERICLES', 'QUO_TRAIT_BIOME_ROMANESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MACEDON', 'LEADER_ALEXANDER', 'QUO_TRAIT_BIOME_ROMANESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ROME', 'LEADER_TRAJAN', 'QUO_TRAIT_BIOME_ROMANESQUE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_WRITER', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARDRADA', 'QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		--('Players:Expansion2_Players', 'CIVILIZATION_SUK_ICELAND', 'LEADER_SUK_INGOLFUR', 'QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SWEDEN', 'LEADER_KRISTINA', 'QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_BERSERKER', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_SCYTHIA', 'LEADER_TOMYRIS', 'QUO_TRAIT_BIOME_ASIAN_STEPPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_GENERAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MONGOLIA', 'LEADER_GENGHIS_KHAN', 'QUO_TRAIT_BIOME_ASIAN_STEPPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_GENERAL', 5) ,

		('Players:Expansion2_Players', 'CIVILIZATION_JAPAN', 'LEADER_HOJO', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_KOREA', 'LEADER_SEONDEOK', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_GITARJA', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_MAORI', 'LEADER_KUPE', 'QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV_DESCRIPTION', 'ICON_IMPROVEMENT_FISHING_BOATS', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_VICTORIA', 'QUO_TRAIT_BIOME_UK_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_UK_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_SCOTLAND', 'LEADER_ROBERT_THE_BRUCE', 'QUO_TRAIT_BIOME_UK_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_UK_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_ENGLAND', 'LEADER_ELEANOR_ENGLAND', 'QUO_TRAIT_BIOME_UK_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_UK_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_ADMIRAL', 5) ,
		
		('Players:Expansion2_Players', 'CIVILIZATION_POLAND', 'LEADER_JADWIGA', 'QUO_TRAIT_BIOME_EAST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5) ,	
		('Players:Expansion2_Players', 'CIVILIZATION_RUSSIA', 'LEADER_PETER_GREAT', 'QUO_TRAIT_BIOME_EAST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5)  ,
		('Players:Expansion2_Players', 'CIVILIZATION_GEORGIA', 'LEADER_TAMAR', 'QUO_TRAIT_BIOME_EAST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5),
		('Players:Expansion2_Players', 'CIVILIZATION_HUNGARY', 'LEADER_MATTHIAS_CORVINUS', 'QUO_TRAIT_BIOME_EAST_EUROPE_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_GOV_DESCRIPTION', 'ICON_UNIT_PIKE_AND_SHOT', 5)		,
		
		('Players:Expansion2_Players', 'CIVILIZATION_PHOENICIA', 'LEADER_DIDO', 'QUO_TRAIT_BIOME_NORTH_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_MERCHANT', 5) ,
		('Players:Expansion2_Players', 'CIVILIZATION_EGYPT', 'LEADER_CLEOPATRA', 'QUO_TRAIT_BIOME_NORTH_AFRICA_GOV', 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_GOV_DESCRIPTION', 'ICON_UNIT_GREAT_MERCHANT', 5)  ;

		
		
-- Handle downloaded leaders
/* CREATE TABLE tblQuoConfig_PlayerItems
(
	yBiomeTrait text,
	yName text,
	yDescription text, 
	yGovernorDescription text,
	yIcon text
) ;

INSERT INTO tblQuoConfig_PlayerItems
		(yBiomeTrait, yName, yDescription, yGovernorDescription, yIcon)
VALUES 	('QUO_TRAIT_BIOME_NEW_WORLD', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_NAME', 'LOC_QUO_TRAIT_BIOME_NEW_WORLD_DESCRIPTION','LOC_QUO_TRAIT_BIOME_NEW_WORLD_GOV_DESCRIPTION','ICON_UNIT_RANGER'),
		('QUO_TRAIT_BIOME_NATIVE_AMERICA', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_NAME', 'LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION','LOC_QUO_TRAIT_BIOME_NATIVE_AMERICA_DESCRIPTION_GOV_DESCRIPTION','ICON_IMPROVEMENT_CAMP'),
		('QUO_TRAIT_BIOME_AFRICA', 'LOC_QUO_TRAIT_BIOME_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_AFRICA_DESCRIPTION','LOC_QUO_TRAIT_BIOME_AFRICA_GOV_DESCRIPTION','ICON_IMPROVEMENT_NAZCA_LINE'),
		('QUO_TRAIT_BIOME_ARABESQUE', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ARABESQUE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION','ICON_UNIT_MISSIONARY'),
		('QUO_TRAIT_BIOME_ASIAN_EXPANSE', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_EXPANSE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_ARABESQUE_GOV_DESCRIPTION','ICON_UNIT_OBSERVATION_BALLOON'),
		('QUO_TRAIT_BIOME_WEST_EUROPE', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_WEST_EUROPE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_WEST_EUROPE_GOV_DESCRIPTION','ICON_IMPROVEMENT_FORT'),
		('QUO_TRAIT_BIOME_ROMANESQUE', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_NAME', 'LOC_QUO_TRAIT_BIOME_ROMANESQUE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_ROMANESQUE_GOV_DESCRIPTION','ICON_UNIT_GREAT_WRITER'),
		('QUO_TRAIT_BIOME_BOREAL_EUROPE', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_BOREAL_EUROPE_GOV_DESCRIPTION','ICON_UNIT_NORWEGIAN_BERSERKER'),
		('QUO_TRAIT_BIOME_ASIAN_STEPPE', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_ASIAN_STEPPE_GOV_DESCRIPTION','ICON_UNIT_GREAT_GENERAL'),
		('QUO_TRAIT_BIOME_ASIAN_PACIFIC', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_NAME', 'LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_DESCRIPTION','LOC_QUO_TRAIT_BIOME_ASIAN_PACIFIC_GOV_DESCRIPTION','ICON_IMPROVEMENT_FISHING_BOATS'),
		('QUO_TRAIT_BIOME_UK', 'LOC_QUO_TRAIT_BIOME_UK_NAME', 'LOC_QUO_TRAIT_BIOME_UK_DESCRIPTION','LOC_QUO_TRAIT_BIOME_UK_GOV_DESCRIPTION','ICON_UNIT_GREAT_ADMIRAL'),
		('QUO_TRAIT_BIOME_EAST_EUROPE', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_NAME', 'LOC_QUO_TRAIT_BIOME_EAST_EUROPE_DESCRIPTION','LOC_QUO_TRAIT_BIOME_EAST_EUROPE_GOV_DESCRIPTION','ICON_UNIT_PIKE_AND_SHOT'),
		('QUO_TRAIT_BIOME_NORTH_AFRICA', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_NAME', 'LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_DESCRIPTION','LOC_QUO_TRAIT_BIOME_NORTH_AFRICA_GOV_DESCRIPTION','ICON_UNIT_GREAT_MERCHANT');

 */
-- abilities
/* SELECT 'Players:Expansion2_Players', tblQuo_Option_FanMadeCivilizations.xCivilizationType, tblQuo_Option_FanMadeCivilizations.xLeaderType, tblQuo_Option_FanMadeCivilizations.xBiomeTrait, tblQuoConfig_PlayerItems.yName, tblQuoConfig_PlayerItems.yDescription, tblQuoConfig_PlayerItems.yIcon, 5
FROM tblQuo_Option_FanMadeCivilizations 
LEFT JOIN tblQuoConfig_PlayerItems on tblQuo_Option_FanMadeCivilizations.xBiomeTrait = tblQuoConfig_PlayerItems.yBiomeTrait ;


-- governors		
SELECT 'Players:Expansion2_Players', tblQuo_Option_FanMadeCivilizations.xCivilizationType, tblQuo_Option_FanMadeCivilizations.xLeaderType, tblQuo_Option_FanMadeCivilizations.xBiomeTrait, 'LOC_QUO_TRAIT_BIOME_GOVERNORS_NAME', tblQuoConfig_PlayerItems.yGovernorDescription, tblQuoConfig_PlayerItems.yIcon, 5
FROM tblQuo_Option_FanMadeCivilizations 
LEFT JOIN tblQuoConfig_PlayerItems on tblQuo_Option_FanMadeCivilizations.xBiomeTrait = tblQuoConfig_PlayerItems.yBiomeTrait ;
 */